POST http://localhost:3006/api/auth/signin
Content-Type: application/json

{
  "email": "pxndxs@pxndxs.com",
  "password": "Hola1234"
}


POST http://localhost:3006/api/auth/signup
Content-Type: application/json

{
  "name": "Pxndxs",
  "lastname": "Ricaldi",
  "birthdate": "1990-01-01",
  "gender": "Male",
  "phone": "123887912",
  "info": "Este usuario es un ejemplo",
  "email": "pxndxs@pxndxs.com",
  "password": "Hola1234"
}

GET http://localhost:3006/api/auth/revalidate-token
Authorization: Bearer <token>
