GET http://localhost:3006/api/team-members

GET http://localhost:3006/api/team-members/:id

POST http://localhost:3006/api/team-members
Authorization: Bearer <token>
Content-Type: application/json

{
  "userId": "4a9fb1ee-a115-417d-a496-aa811db52f1c",
  "teamId": "646b761e-0580-484c-b02a-cdb2cffbf437"
}

PATCH http://localhost:3006/api/team-members/:id
Authorization: Bearer <token>
Content-Type: application/json

{
  "name": "Pxndxs 2",
  "details": "Estos son los detalles de la empresa",
  "imageUrl": "https://pxndxs.com/image.png",
  "companyId": "2714b9b7-5e6a-4bf4-a73e-aa108b3742e5" 
}

DELETE http://localhost:3006/api/team-members/:id
Authorization: Bearer <token>
