GET http://localhost:3006/api/teams

GET http://localhost:3006/api/teams/:id

POST http://localhost:3006/api/teams
Authorization: Bearer <token>
Content-Type: application/json

{
  "name": "Pxndxs 2",
  "details": "Estos son los detalles de la empresa",
  "imageUrl": "https://pxndxs.com/image.png"
}

PATCH http://localhost:3006/api/teams/:id
Authorization: Bearer <token>
Content-Type: application/json

{
  "name": "Pxndxs 2",
  "details": "Estos son los detalles de la empresa",
  "imageUrl": "https://pxndxs.com/image.png"
}

DELETE http://localhost:3006/api/teams/:id
Authorization: Bearer <token>
