GET http://localhost:3006/api/users

GET http://localhost:3006/api/users/:id

POST http://localhost:3006/api/users
Authorization: Bearer <token>
Content-Type: application/json

{
  "name": "Pxndxs 2",
  "lastname": "Last Pxndxs 2",
  "birthdate": "1990-01-01",
  "gender": "Male",
  "phone": "123887912",
  "info": "Este usuario es un segundo ejemplo",
  "email": "pxndxs2@pxndxs.com",
  "password": "Hola1234",
  "role": "ADMIN"
}

PATCH http://localhost:3006/api/users/:id
Content-Type: application/json

{
  "name": "Pxndxs xD",
  "email": "pxndxsxd@pxndxs.com",
  "password": "Hola12345",
  "role": "USER"
}

DELETE http://localhost:3006/api/users/:id
