GET http://localhost:3006/api/users

GET http://localhost:3006/api/users/:id

POST http://localhost:3006/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc3ODgzYjRiLTY2NDktNDViNi04ODFhLTk1OWYzODE1ZjFiNyIsImlhdCI6MTcwMzIwMTAyMSwiZXhwIjoxNzAzMjg3NDIxfQ.yTabr5sl1mNQbYHJcEMxazUkVUNZIbRMRen9_gUEuOo
Content-Type: application/json

{
  "name": "Pxndxs",
  "email": "pxndxs12@pxndxs.com",
  "password": "Hola1234",
  "role": "ADMIN"
}

PATCH http://localhost:3006/api/users/:id
Content-Type: application/json

{
  "name": "Pxndxs xD",
  "email": "pxndxsxd@pxndxs.com",
  "password": "Hola12345",
  "role": "USER"
}

DELETE http://localhost:3006/api/users/:id
